class Data2d{
    //Constructor
    constructor(nPoints){
        this.x = [];
        this.y = [];
        for (let i = 0; i < nPoints; i++){
            this.x.push(Math.floor(Math.random() * Math.floor(nPoints)))
            this.y.push(Math.floor(Math.random() * Math.floor(nPoints)))
        }
    }
    //Points
    points(){
        let points = []
        for (let i = 0; i < this.x.length; i++){
            if (this.x[i] > this.y[i]){
                points.push({x:this.x[i], y:this.y[i], label:1})
            }else {
                points.push({x:this.x[i], y:this.y[i], label:-1})
            }
        }
        return points
    }
    //Build graphical objects
    //Not bound to the data generated by the objects so it can plot any data no matter the origin
    plot(points,c1, c2){
        let cat1 = {
            x : [],
            y : [],
            name : c1,
            text: []
        }
        let cat2 = {
            x : [],
            y : [],
            name : c2,
            text: []
        }
        for (let i = 0; i < points.length; i++){
            if (points[i].label == 1){
                cat1.x.push(points[i].x)
                cat1.y.push(points[i].y)
                cat1.text.push(`${points[i].x}-${points[i].y}-L(${points[i].label})`)
            } else {
                cat2.x.push(points[i].x)
                cat2.y.push(points[i].y)
                cat2.text.push(`${points[i].x}-${points[i].y}-L(${points[i].label})`)
            }
        }
        return [cat1, cat2]
    }
}

module.exports = Data2d